import PDFDocument from "pdfkit";
import Threat from "../models/Threat.js";
import LoginHistory from "../models/LoginHistory.js";

// GET /api/reports/download-pdf
// Generates a real PDF summarizing actual data from MongoDB — not a
// pre-made static file. Every number in this document comes from a live
// query at the moment of download.
export async function downloadReportPdf(req, res) {
  try {
    const openThreats = await Threat.find({ status: "open" }).sort({ createdAt: -1 });
    const allThreats = await Threat.find().sort({ createdAt: -1 }).limit(15);
    const since24h = new Date(Date.now() - 24 * 60 * 60 * 1000);
    const failedLogins24h = await LoginHistory.countDocuments({ success: false, createdAt: { $gte: since24h } });

    const typeCounts = {};
    allThreats.forEach((t) => { typeCounts[t.type] = (typeCounts[t.type] || 0) + 1; });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="cyberintel-security-report-${Date.now()}.pdf"`);

    const doc = new PDFDocument({ margin: 50 });
    doc.pipe(res);

    // Header
    doc.fontSize(22).fillColor("#0d0f1a").text("CyberIntel Security Report", { align: "left" });
    doc.fontSize(10).fillColor("#6b7488").text(`Generated: ${new Date().toLocaleString()}`);
    doc.moveDown(1.5);

    // Summary
    doc.fontSize(14).fillColor("#0d0f1a").text("Summary");
    doc.moveDown(0.3);
    doc.fontSize(11).fillColor("#333333");
    doc.text(`Open threats: ${openThreats.length}`);
    doc.text(`Failed login attempts (last 24h): ${failedLogins24h}`);
    doc.text(`Total threats on record (most recent 15 shown below): ${allThreats.length}`);
    doc.moveDown(1);

    // Threats by type
    doc.fontSize(14).fillColor("#0d0f1a").text("Threats by Type");
    doc.moveDown(0.3);
    doc.fontSize(11).fillColor("#333333");
    if (Object.keys(typeCounts).length === 0) {
      doc.text("No threats recorded yet.");
    } else {
      Object.entries(typeCounts).forEach(([type, count]) => {
        doc.text(`${type}: ${count}`);
      });
    }
    doc.moveDown(1);

    // Recent threats table
    doc.fontSize(14).fillColor("#0d0f1a").text("Recent Threats");
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor("#333333");
    if (allThreats.length === 0) {
      doc.text("No threats recorded yet — this report will populate as real activity occurs.");
    } else {
      allThreats.forEach((t) => {
        doc.fillColor("#0d0f1a").text(`• ${t.title}`, { continued: false });
        doc.fillColor("#6b7488").fontSize(9).text(
          `  ${t.type} — ${t.severity} severity — ${t.status} — ${new Date(t.createdAt).toLocaleString()}`
        );
        doc.fontSize(10);
        doc.moveDown(0.4);
      });
    }

    doc.moveDown(1);
    doc.fontSize(9).fillColor("#9aa4bd").text(
      "Generated by CyberIntel — a final-year cybersecurity major project. All data above is live, pulled directly from MongoDB at the time of generation.",
      { align: "left" }
    );

    doc.end();
  } catch (err) {
    console.error("PDF report generation failed:", err.message);
    res.status(500).json({ message: "Report generation failed", error: err.message });
  }
} 

// GET /api/reports/download-activity
// Returns a JSON file containing all login history entries (user activity)
export async function downloadActivityLog(req, res) {
  try {
    // Fetch all login attempts, most recent first
    const activities = await LoginHistory.find()
      .populate('user', 'email name')
      .sort({ createdAt: -1 });

    // Prepare data for download – keep essential fields
    const payload = activities.map((a) => ({
      userId: a.user ? a.user._id : null,
      email: a.email,
      success: a.success,
      reason: a.reason,
      ip: a.ip,
      timestamp: a.createdAt,
    }));

    res.setHeader('Content-Type', 'application/json');
    res.setHeader(
      'Content-Disposition',
      `attachment; filename="activity-log-${Date.now()}.json"`
    );
    res.send(JSON.stringify(payload, null, 2));
  } catch (err) {
    console.error('Activity log download failed:', err.message);
    res.status(500).json({ message: 'Activity log download failed', error: err.message });
  }
}